In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

In [2]:
cv2.__version__

'3.4.2'

In [3]:
path = "/content/clouderizer/catdogs/data/train"
print(len(os.listdir(path)))


25000


In [ ]:
training_data = []
IMG_SIZE = 100

print(os.listdir(path)[:10])
for img in os.listdir(path):
    try:
        class_num = 0 if img[0:3] == 'dog' else 1 #Filenames begins with dog or cat. If first three character of the filename is dog
        img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
        new_array = cv2.resize(img_array, (IMG_SIZE,IMG_SIZE))
        training_data.append([new_array, class_num])
        #print(img_array.shape)
        #plt.imshow(img_array,cmap='gray')
        #plt.show()
        #print(img)
    except Exceptinon as e:
        print(e)
        

In [ ]:
print(img_array.shape)
plt.imshow(new_array,cmap='gray')
plt.show()

In [ ]:
training_data[0]
plt.imshow(training_data[0], cmap='gray')
plt.show()

In [17]:
import random
print(len(training_data))
random.shuffle(training_data)

25000


In [18]:
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)
    

In [23]:
print(X[0])
X[0].shape

[[183 180 197 ... 158 177 188]
 [194 173 181 ... 161 174 177]
 [192 179 209 ... 161 169 175]
 ...
 [241 239 236 ... 213 206  92]
 [239 235 235 ... 194 186 101]
 [234 230 230 ... 180 172 104]]


(100, 100)

In [34]:
X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)

In [39]:
print(X[1])
X[1].shape

[[[131]
  [135]
  [137]
  ...
  [166]
  [162]
  [163]]

 [[130]
  [134]
  [134]
  ...
  [166]
  [167]
  [160]]

 [[134]
  [128]
  [134]
  ...
  [157]
  [164]
  [165]]

 ...

 [[140]
  [143]
  [146]
  ...
  [154]
  [169]
  [142]]

 [[158]
  [139]
  [156]
  ...
  [166]
  [139]
  [148]]

 [[154]
  [151]
  [140]
  ...
  [142]
  [160]
  [157]]]


(100, 100, 1)

In [37]:
import pickle

pickle_out = open("X.pickle", "wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle", "wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [38]:
pickle_in = open("X.pickle", "rb")
X = pickle.load(pickle_in)
print(X[1])

[[[131]
  [135]
  [137]
  ...
  [166]
  [162]
  [163]]

 [[130]
  [134]
  [134]
  ...
  [166]
  [167]
  [160]]

 [[134]
  [128]
  [134]
  ...
  [157]
  [164]
  [165]]

 ...

 [[140]
  [143]
  [146]
  ...
  [154]
  [169]
  [142]]

 [[158]
  [139]
  [156]
  ...
  [166]
  [139]
  [148]]

 [[154]
  [151]
  [140]
  ...
  [142]
  [160]
  [157]]]
